### ISSUE TITLE
加载插件时产生了报错

### ISSUE THREAD

**Issue by hui6688a** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#29]
TS3版本使用1.1的整合包
载入插件时提示以下错误：
2023-09-04 09:56:10.0456| INFO|Core|Setup.LogHeader [============ TS3AudioBot started =============]
2023-09-04 09:56:10.0882| INFO|Core|Setup.LogHeader [ Date: Monday, 04 September 2023 09:56:10
2023-09-04 09:56:10.1525| INFO|Core|Setup.LogHeader [ Version: <?>/<?>/<?>
2023-09-04 09:56:10.1529| INFO|Core|Setup.LogHeader [ Build: <?>
2023-09-04 09:56:10.1529| INFO|Core|Setup.LogHeader [ Platform: CentOS Linux 7 (Core) (64bit)
2023-09-04 09:56:10.1529| INFO|Core|Setup.LogHeader [ Runtime: .NET Framework 3.1.32 ServerGC:False GC:SustainedLowLatency
2023-09-04 09:56:10.1540| INFO|Core|Setup.LogHeader [ Opus: libopus 1.0.2 (x64)
2023-09-04 09:56:10.1540| INFO|Core|Setup.LogHeader [==============================================]
2023-09-04 09:56:10.6297| WARN|Core|RightsManager.CreateConfigIfNotExists No permission file found.
2023-09-04 09:57:36.0804| INFO|Core|RightsManager.CreateConfig Creating new permission file ({"AdminUids":["3uuPq0HsIwOjpsJCxwzgZ931fCo="], "OverwriteIfExists":false})
2023-09-04 09:57:36.1180|ERROR|Core|WebServer.StartWebServerInternal Can't find a WebInterface path to host. Try specifying the path to host in the config
2023-09-04 09:57:36.1180| INFO|Core|WebServer.StartWebServerInternal Starting Webserver on port 58913
2023-09-04 09:57:55.6114| INFO|Core|Bot.Run Bot "default" connecting to "g.ts3.plus"
2023-09-04 09:57:55.9946| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: D3 AD 47 5D 78 56 EB 5D 00 00 A6 00 01 
2023-09-04 09:57:55.9958| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: EC 43 74 CA 97 0A 89 21 00 01 26 4D C5 
2023-09-04 09:57:56.1314| INFO|Core|Ts3Client.ConnectClient Client connected.
2023-09-04 09:58:13.0392| INFO|0|Bot.OnMessageReceived User Miu requested: !plugin load 0
2023-09-04 09:58:13.2060|FATAL|0|Core.UnhandledExceptionHandler Critical program failure!
System.DllNotFoundException: Unable to load shared library 'kernel32' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32: cannot open shared object file: No such file or directory
   at IniFile.GetPrivateProfileString(String Section, String Key, String Default, StringBuilder RetVal, Int32 Size, String FilePath)
   at IniFile.Read(String Key, String Section)
   at YunPlgun.Initialize()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2023-09-04 09:58:13.2188| INFO|0|Core.StopAsync TS3AudioBot shutting down.

**Comment by ZHANGTIANYAO1** [comment]
emmm似乎是因为调用了一个windows的dll库但是linux里面没有导致的，我得研究一下

**Comment by ZHANGTIANYAO1** [comment]
[YunBot.zip](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/files/12509392/YunBot.zip)
试试这个

**Comment by hui6688a** [comment]
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'kernel32' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32: cannot open shared object file: No such file or directory
   at IniFile.GetPrivateProfileString(String Section, String Key, String Default, StringBuilder RetVal, Int32 Size, String FilePath)
   at IniFile.Read(String Key, String Section)
   at YunPlgun.Initialize()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
已放弃

**Comment by hui6688a** [comment]
仍然提示该错误，使用的是1.1版本中的整合包并替换的最新插件

**Comment by ZHANGTIANYAO1** [comment]
这个问题暂时没法解决，正如我说的，此插件主要还是面对windows系统，可能是新的编译环境导致无法在linux上使用，但是需要更多的调查，我暂时无法给出修复时间

**Comment by ZHANGTIANYAO1** [comment]
目前只能说是使用旧的版本

**Comment by hui6688a** [comment]
好呢，辛苦了

**Comment by FiveHair** [comment]
> 这个问题暂时没法解决，正如我说的，此插件主要还是面对windows系统，可能是新的编译环境导致无法在linux上使用，但是需要更多的调查，我暂时无法给出修复时间

linux没有kernel32.dll，可以抛弃它来做兼容。我使用Nini可以在linux操作ini，但是需要添加Costura.Fody来打包，我研究下怎么提pr吧😂

**Comment by FiveHair** [comment]
> 好呢，辛苦了

我fork了一下代码做了点兼容，你试试这个
[YunPlugin-UNM.zip](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/files/12536615/YunPlugin-UNM.zip)

**Comment by ZHANGTIANYAO1** [comment]
NB，我之前没有接触过linux开发，学习到了

**Comment by FiveHair** [comment]
> NB，我之前没有接触过linux开发，学习到了

我也是边弄边百度哈哈

**Comment by lazywoo** [comment]
@FiveHair 给出的YunPlugin-UNM如何使用呢，没用过c#，作者给出的插件在linux跑会报错😭
