### ISSUE TITLE
使用自建API报告：An unexpected error occurred: The remote server returned an error: (502) Bad Gateway.

### ISSUE THREAD

**Issue by WorldSansha** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#40]
插件版本：2.0.3
TS3AudioBot版本：本项目releases内的整合包
网易云API版本：4.13.8
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/37899975/6b754651-cb27-490d-8191-c30c01f8eaad)

**Comment by ZHANGTIANYAO1** [comment]
请上传完整日志文件（log）

**Comment by WorldSansha** [comment]
> 请上传完整日志文件（log）

2023-10-28 15:22:41.4148| INFO|Core|Setup.LogHeader [============ TS3AudioBot started =============]
2023-10-28 15:22:41.4402| INFO|Core|Setup.LogHeader [ Date: Saturday, 28 October 2023 15:22:41
2023-10-28 15:22:41.4552| INFO|Core|Setup.LogHeader [ Version: <?>/<?>/<?>
2023-10-28 15:22:41.4552| INFO|Core|Setup.LogHeader [ Build: <?>
2023-10-28 15:22:41.4582| INFO|Core|Setup.LogHeader [ Platform: Windows 6.2.9200.0 (64bit)
2023-10-28 15:22:41.4582| INFO|Core|Setup.LogHeader [ Runtime: .NET Framework 3.1.32 ServerGC:True GC:SustainedLowLatency
2023-10-28 15:22:41.4582| INFO|Core|Setup.LogHeader [ Opus: libopus 1.2.1-fixed (x64)
2023-10-28 15:22:41.4582| INFO|Core|Setup.LogHeader [==============================================]
2023-10-28 15:22:41.7425| INFO|Core|WebServer.StartWebServerInternal Starting Webserver on port 58913
2023-10-28 15:22:41.8939| INFO|Core|Bot.Run Bot "default" connecting to "192.168.31.14:9987"
2023-10-28 15:22:42.1182| INFO|Core|Ts3Client.ConnectClient Client connected.
2023-10-28 15:22:47.5757| INFO|0|Bot.OnMessageReceived User WorldSansha requested: !plugin load 0
2023-10-28 15:22:47.6092| WARN|0|RightsManager.ReadFile Right "cmd.yun.play" is not registered.
2023-10-28 15:22:47.6092| WARN|0|RightsManager.ReadFile Right "cmd.yun.playid" is not registered.
2023-10-28 15:22:47.6092| WARN|0|RightsManager.ReadFile Right "cmd.yun.gedan" is not registered.
2023-10-28 15:22:47.6092| WARN|0|RightsManager.ReadFile Right "cmd.yun.mode" is not registered.
2023-10-28 15:22:47.6144| WARN|0|RightsManager.ReadFile Right "cmd.yun.gedanid" is not registered.
2023-10-28 15:22:47.6144| WARN|0|RightsManager.ReadFile Right "cmd.yun.next" is not registered.
2023-10-28 15:22:47.6144| WARN|0|RightsManager.ReadFile Right "cmd.yun.login" is not registered.
2023-10-28 15:22:47.6144| WARN|0|RightsManager.ReadFile Right "cmd.yun.add" is not registered.
2023-10-28 15:22:47.6144| WARN|0|RightsManager.ReadFile Right "cmd.yun.play" is not registered.
2023-10-28 15:22:47.6144| WARN|0|RightsManager.ReadFile Right "cmd.yun.playid" is not registered.
2023-10-28 15:22:47.6144| WARN|0|RightsManager.ReadFile Right "cmd.yun.gedan" is not registered.
2023-10-28 15:22:47.6144| WARN|0|RightsManager.ReadFile Right "cmd.yun.mode" is not registered.
2023-10-28 15:22:47.6144| WARN|0|RightsManager.ReadFile Right "cmd.yun.gedanid" is not registered.
2023-10-28 15:22:47.6144| WARN|0|RightsManager.ReadFile Right "cmd.yun.next" is not registered.
2023-10-28 15:22:47.6144| WARN|0|RightsManager.ReadFile Right "cmd.yun.login" is not registered.
2023-10-28 15:22:47.6144| WARN|0|RightsManager.ReadFile Right "cmd.yun.add" is not registered.
2023-10-28 15:22:54.0683| INFO|0|Bot.OnMessageReceived User WorldSansha requested: !plugin list
2023-10-28 15:23:00.7851| INFO|0|Bot.OnMessageReceived User WorldSansha requested: !yun login
2023-10-28 15:23:00.8627|ERROR|0|Bot.TryCatchCommand Unexpected command error: The remote server returned an error: (502) Bad Gateway.
System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.GetResponse()
   at YunPlgun.HttpGet(String url)
   at YunPlgun.CommanloginAsync(Ts3Client ts3Client, TsFullClient tsClient)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.CommandManager.Execute(ExecutionInformation info, String command)
   at TS3AudioBot.Bot.<>c__DisplayClass42_0.<<CallScript>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at TS3AudioBot.Bot.TryCatchCommand(ExecutionInformation info, Boolean answer, Func`1 action)

**Comment by ZHANGTIANYAO1** [comment]
检查一下服务器防火墙和代理设置

**Comment by WorldSansha** [comment]
> 检查一下服务器防火墙和代理设置

解决了，Windows内的代理设置没勾选不代理本地地址
