### ISSUE TITLE
歌单超过1200首歌，报错

### ISSUE THREAD

**Issue by Kevinwu901113** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#78]
System.Text.Json.JsonException: '{' is invalid after a single JSON value. Expected end of data. Path: $ | LineNumber: 0 | BytePositionInLine: 33.
 ---> System.Text.Json.JsonReaderException: '{' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 33.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, JsonReaderException ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at YunPlgun.genList(Int64 id, ArrayList SongQueue, Ts3Client ts3Client)
   at YunPlgun.playgedan(Int64 id, PlayManager playManager, InvokerData invoker, Ts3Client ts3Client, Player player)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters) in /home/kevin/TS3AudioBot-NetEaseCloudmusic-plugin/TS3AudioBot/CommandSystem/Commands/FunctionCommand.cs:line 111
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/kevin/TS3AudioBot-NetEaseCloudmusic-plugin/TS3AudioBot/CommandSystem/Commands/FunctionCommand.cs:line 206
   at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/kevin/TS3AudioBot-NetEaseCloudmusic-plugin/TS3AudioBot/CommandSystem/BotCommand.cs:line 132
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/kevin/TS3AudioBot-NetEaseCloudmusic-plugin/TS3AudioBot/CommandSystem/Commands/CommandGroup.cs:line 64
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/kevin/TS3AudioBot-NetEaseCloudmusic-plugin/TS3AudioBot/CommandSystem/Commands/CommandGroup.cs:line 64
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/kevin/TS3AudioBot-NetEaseCloudmusic-plugin/TS3AudioBot/CommandSystem/Commands/RootCommand.cs:line 42
   at TS3AudioBot.CommandSystem.CommandManager.Execute(ExecutionInformation info, String command) in /home/kevin/TS3AudioBot-NetEaseCloudmusic-plugin/TS3AudioBot/CommandSystem/CommandManager.cs:line 402
   at TS3AudioBot.Bot.<>c__DisplayClass42_0.<<CallScript>b__0>d.MoveNext() in /home/kevin/TS3AudioBot-NetEaseCloudmusic-plugin/TS3AudioBot/Bot.cs:line 499
--- End of stack trace from previous location where exception was thrown ---
   at TS3AudioBot.Bot.TryCatchCommand(ExecutionInformation info, Boolean answer, Func`1 action) in /home/kevin/TS3AudioBot-NetEaseCloudmusic-plugin/TS3AudioBot/Bot.cs:line 538

**Comment by Kevinwu901113** [comment]
了解谢谢
