### ISSUE TITLE
cpu占用异常

### ISSUE THREAD

**Issue by LovelyRua** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#9]
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/81335837/8e07aa92-3343-41a7-aadf-d6d95ab0dc85)
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/81335837/21a325f7-31ad-491c-80c1-68e0d9fd2dd8)
web面板中显示的cpu占用是正常的 但是在任务管理器里看占用了过多的cpu
刚开始用的时候好像没有这个问题 现在莫名其妙出现了额外的占用

**Comment by LovelyRua** [comment]
可能是数据库的问题 把6000kb的.db删除重建后cpu占用就恢复正常了 重置数据库之前爆了一条错误
07:59:56.4873|ERROR|Api| LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00.
   at LiteDB.LockService.Read()
   at LiteDB.LiteEngine.Find(String collection, Query query, Int32 skip, Int32 limit)+MoveNext()
   at LiteDB.LiteEngine.Find(String collection, Query query, String[] includes, Int32 skip, Int32 limit)+MoveNext()
   at LiteDB.LiteCollection`1.Find(Query query, Int32 skip, Int32 limit)+MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at LiteDB.LiteCollection`1.FindById(BsonValue id)
   at TS3AudioBot.Sessions.TokenManager.GetToken(String authId)
   at TS3AudioBot.Web.Api.WebApi.Authenticate(HttpRequest request)
   at TS3AudioBot.Web.Api.WebApi.ProcessApiV1Call(HttpContext context)
   at NLog.Logger.SwallowAsync(Func`1 asyncAction)
